{
 "title": "Etcd - Detailed",
 "description": "Etcd Dashboard from Prometheus for clusters running etcd as Kubernetes Pods",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(etcd_server_has_leader, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(etcd_server_has_leader{namespace=\"$namespace\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(etcd_server_has_leader{job=\"$cluster\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Etcd Members",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_id{pod=~\"$pod\",job=~\"$cluster\"})",
     "legendFormat": "members"
    }
   ]
  },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{pod=~\"$pod\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "The total number of failed proposals seen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{pod=~\"$pod\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{pod=~\"$pod\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\",\njob=~\"$cluster\"}"
    },
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"})*100"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_keys_total{pod=~\"$pod\",job=~\"$cluster\"}) by (instance)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{pod=~\"$pod\",job=~\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{pod=~\"$pod\",job=~\"$cluster\"}[5m])) by (instance, le))"
    },
    {
     "expr": "sum(etcd_server_is_leader{pod=~\"$pod\",job=~\"$cluster\"}) by (instance)"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_db_compaction_keys_total{pod=~\"$pod\",job=~\"$cluster\"}) by (instance)"
    }
   ]
  },
  {
   "title": "DB Info per Member",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "% DB Space Used $pod",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "Urgent Defragmentation ? $pod",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"} / etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "DB Left capacity (with fragmented space) $pod",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"} - etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
       "legendFormat": "Backend bytes - DB Size"
      }
     ]
    },
    {
     "title": "DB Size Limit (Backend-bytes) $pod",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "etcd_server_quota_backend_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
       "legendFormat": "{{ pod }} Quota Bytes"
      }
     ]
    }
   ]
  },
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_keys_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} Num keys"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{pod=~\"$pod\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ pod }} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{pod=~\"$pod\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ pod }} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{pod=~\"$pod\",job=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{ pod }} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{pod=~\"$pod\",job=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{ pod }} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Key Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_mvcc_put_total{pod=~\"$pod\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ pod }} puts/s"
    },
    {
     "expr": "rate(etcd_mvcc_delete_total{pod=~\"$pod\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ pod }} deletes/s"
    }
   ]
  },
  {
   "title": "Members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_id{pod=~\"$pod\",job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Slow operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_slow_apply_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} slow applies"
    },
    {
     "expr": "etcd_server_slow_read_indexes_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} slow read indexes"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} Resident Memory"
    }
   ]
  },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\",pod=~\"$pod\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\",pod=~\"$pod\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",pod=~\"$pod\",job=~\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\",pod=~\"$pod\",job=~\"$cluster\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",pod=~\"$pod\",job=~\"$cluster\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\",pod=~\"$pod\",job=~\"$cluster\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} DB Size"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} Used bytes"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_heartbeat_send_failures_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} heartbeat  failures"
    },
    {
     "expr": "etcd_server_health_failures{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod }} health failures"
    }
   ]
  },
  {
   "title": "Defrag time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_backend_defrag_duration_seconds_sum{pod=~\"$pod\",job=~\"$cluster\"}[1m])",
     "legendFormat": "{{ pod }} latency distributions of defrag"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{pod=~\"$pod\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{pod=~\"$pod\",job=~\"$cluster\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{pod=~\"$pod\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{pod=~\"$pod\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Compacted Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_compaction_keys_total{pod=~\"$pod\",job=~\"$cluster\"}",
     "legendFormat": "{{ pod  }} keys compacted "
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "graph",
   "description": "indicates how many proposals are queued to commit. Rising pending proposals suggests there is a high client load or the member cannot commit proposals.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending{pod=~\"$pod\",job=~\"$cluster\"})",
     "legendFormat": "Proposals pending"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_sum{pod=~\"$pod\",job=~\"$cluster\"}[1m])",
     "legendFormat": "{{ pod }} The latency distributions of fsync called by wal"
    },
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_sum{pod=~\"$pod\",job=~\"$cluster\"}[1m])",
     "legendFormat": "{{ pod }} The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{pod=~\"$pod\",job=~\"$cluster\"}[1d])",
     "legendFormat": "{{ pod }} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "Compaction rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_db_compaction_keys_total{pod=~\"$pod\",job=~\"$cluster\"}[5m])",
     "legendFormat": "{{ pod }} compact/s"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "graph",
   "description": "proposals_committed_total records the total number of consensus proposals committed. This gauge should increase over time if the cluster is healthy. Several healthy members of an etcd cluster may have different total committed proposals at once. This discrepancy may be due to recovering from peers after starting, lagging behind the leader, or being the leader and therefore having the most commits. It is important to monitor this metric across all the members in the cluster; a consistently large lag between a single member and its leader indicates that member is slow or unhealthy.\n\nproposals_applied_total records the total number of consensus proposals applied. The etcd server applies every committed proposal asynchronously. The difference between proposals_committed_total and proposals_applied_total should usually be small (within a few thousands even under high load). If the difference between them continues to rise, it indicates that the etcd server is overloaded. This might happen when applying expensive queries like heavy range queries or large txn operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{pod=~\"$pod\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "total number of consensus proposals committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{pod=~\"$pod\",job=~\"$cluster\"}[5m]))",
     "legendFormat": "total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{pod=~\"$pod\",job=~\"$cluster\"}[1m]))",
     "legendFormat": "The total latency distributions of save called by snapshot"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{pod=~\"$pod\",job=~\"$cluster\"}[1m]))",
     "legendFormat": "The total number of bytes received by grpc clients"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{pod=~\"$pod\",job=~\"$cluster\"}[1m]))",
     "legendFormat": "The total number of bytes sent to grpc clients"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{pod=~\"$pod\", job=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{ pod }} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{pod=~\"$pod\", job=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{ pod }} DB fsync"
    }
   ]
  }
 ]
}