{
 "title": "Wireguard",
 "description": "Metrics for Wireguard VPN",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Wireguard Server",
    "query": {
     "query": "label_values(wireguard_received_bytes_total, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connected Clients (Total Bandwidth)",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (rate(wireguard_sent_bytes_total{service=\"$service\"}[$__rate_interval]) + rate(wireguard_received_bytes_total{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (rate(wireguard_received_bytes_total{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Send Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (rate(wireguard_sent_bytes_total{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Latest Handshakes (Seconds)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (rate(wireguard_latest_handshake_seconds{service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}