{
 "title": "ZooKeeper Dashboard",
 "description": "ZooKeeper Dashboard for Prometheus metrics scraper",
 "tags": [
  "Altinity",
  "zookeeper"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "job", "label": "Scraping Job", "query": "label_values(znode_count,job)" },
   {
    "name": "namespace",
    "label": "K8S Namespace",
    "query": "label_values(znode_count{job=~\"$job\"}, namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values(znode_count{job=~\"$job\",namespace=~\"$namespace\"}, pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "znode_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} znode_count"
    },
    {
     "expr": "ephemerals_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} ephemerals"
    }
   ]
  },
  {
   "title": "znode_count_rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(znode_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} znode_count_rate"
    },
    {
     "expr": "rate(ephemerals_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} ephemerals_rate"
    }
   ]
  },
  {
   "title": "global_sessions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "global_sessions{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}}"
    }
   ]
  },
  {
   "title": "local_sessions ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "local_sessions{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}}"
    }
   ]
  },
  {
   "title": "write_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(write_per_namespace_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} write_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "read_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(read_per_namespace_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} read_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "approximate_data_size{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} approximate_data_size"
    }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(packets_received{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} packets_received"
    }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(packets_sent{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} packets_sent"
    }
   ]
  },
  {
   "title": "response_packet_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(response_packet_cache_hits{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / (increase(response_packet_cache_misses{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) + increase(response_packet_cache_hits{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]))",
     "legendFormat": "{{pod_name}}.{{namespace}} response_packet_cache_hits_rate"
    },
    {
     "expr": "increase(response_packet_get_children_cache_hits{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / (increase(response_packet_get_children_cache_misses{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) + increase(response_packet_get_children_cache_hits{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])) ",
     "legendFormat": "{{pod_name}}.{{namespace}} response_packet_get_children_cache_hits_rate"
    }
   ]
  },
  {
   "title": "unrecoverable_error_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(unrecoverable_error_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} unrecoverable_error_count"
    }
   ]
  },
  {
   "title": "digest_mismatches_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(digest_mismatches_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} digest_mismatches_count"
    }
   ]
  },
  {
   "title": "startup_snap_load_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(startup_snap_load_time_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(startup_snap_load_time_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} startup_snap_load_time"
    }
   ]
  },
  {
   "title": "startup_txns_loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(startup_txns_loaded_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(startup_txns_loaded_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} startup_txns_loaded"
    }
   ]
  },
  {
   "title": "db_init_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dbinittime_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} db_init_time"
    }
   ]
  },
  {
   "title": "Quorum/Leader Election",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "quorum_size",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(quorum_size{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"})",
       "legendFormat": "quorum_size"
      }
     ]
    },
    {
     "title": "leader",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
     "format": "ms",
     "valueName": "name",
     "targets": [
      {
       "expr": "leader_uptime{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}}"
      }
     ]
    },
    {
     "title": "leader_uptime",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "leader_uptime{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} leader_uptime"
      }
     ]
    },
    {
     "title": "learner/observer",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(learners{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"})",
       "legendFormat": "learners"
      },
      {
       "expr": "max(synced_non_voting_followers{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"})",
       "legendFormat": "synced_non_voting_followers"
      },
      {
       "expr": "max(synced_observers{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"})",
       "legendFormat": "synced_observers"
      }
     ]
    },
    {
     "title": "election_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "increase(election_time_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(election_time_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
       "legendFormat": "{{pod_name}}.{{namespace}} election_avg_time"
      }
     ]
    },
    {
     "title": "quorum uptime",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "uptime{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} uptime"
      }
     ]
    },
    {
     "title": "learner_commit_received_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "learner_commit_received_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} learner_commit_received_count"
      }
     ]
    },
    {
     "title": "commit_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "commit_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} commit_count"
      }
     ]
    },
    {
     "title": "snap_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "snap_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} snap_count"
      }
     ]
    },
    {
     "title": "diff_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "diff_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} diff_count"
      }
     ]
    },
    {
     "title": "looking_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "looking_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} looking_count"
      }
     ]
    },
    {
     "title": "proposal_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "proposal_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} proposal_count"
      }
     ]
    },
    {
     "title": "proposal_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "last_proposal_size{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} last_proposal_size"
      },
      {
       "expr": "max_proposal_size{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} max_proposal_size"
      },
      {
       "expr": "min_proposal_size{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} min_proposal_size"
      }
     ]
    },
    {
     "title": "follower_sync_time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(follower_sync_time_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
       "legendFormat": "{{pod_name}}.{{namespace}} follower_sync_time"
      }
     ]
    },
    {
     "title": "learner_handler_qp_size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "learner_handler_qp_size_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} learner_handler_qp_size_sum sid:{{key}}"
      }
     ]
    },
    {
     "title": "quit_leading_due_to_disloyal_voter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "quit_leading_due_to_disloyal_voter{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
       "legendFormat": "{{pod_name}}.{{namespace}} quit_leading_due_to_disloyal_voter"
      }
     ]
    },
    {
     "title": "Observer Master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(om_commit_process_time_ms_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
       "legendFormat": "{{pod_name}}.{{namespace}} om_commit_process_time"
      },
      {
       "expr": "rate(om_proposal_process_time_ms_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
       "legendFormat": "{{pod_name}}.{{namespace}} om_proposal_process_time"
      }
     ]
    }
   ]
  },
  { "title": "Session/Watch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "watch_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} watch_count"
    }
   ]
  },
  {
   "title": "node_changed_watch_triggered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_changed_watch_count_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} node_changed_watch_count"
    }
   ]
  },
  {
   "title": "node_children_watch_triggered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_children_watch_count_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} node_children_watch_count"
    }
   ]
  },
  {
   "title": "node_deleted_watch_triggered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_deleted_watch_count_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} node_deleted_watch_count"
    }
   ]
  },
  {
   "title": "node_created_watch_triggered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_created_watch_count_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} node_created_watch_count"
    }
   ]
  },
  {
   "title": "revalidate_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(revalidate_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} revalidate_count"
    }
   ]
  },
  {
   "title": "stale_sessions_expired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(stale_sessions_expired{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} stale_sessions_expired"
    }
   ]
  },
  {
   "title": "dead_watchers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(dead_watchers_cleared{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} dead_watchers_cleared"
    },
    {
     "expr": "irate(dead_watchers_queued{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} dead_watchers_queued"
    },
    {
     "expr": "increase(dead_watchers_cleaner_latency_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(dead_watchers_cleaner_latency_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} dead_watchers_cleaner_latency_avg"
    }
   ]
  },
  {
   "title": "add_dead_watcher_stall_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(add_dead_watcher_stall_time{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} add_dead_watcher_stall_time"
    }
   ]
  },
  { "title": "Client/Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_requests{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} outstanding_requests"
    }
   ]
  },
  {
   "title": "client_response_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "last_client_response_size{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} last_client_response_size"
    },
    {
     "expr": "min_client_response_size{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} min_client_response_size"
    },
    {
     "expr": "max_client_response_size{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} max_client_response_size"
    }
   ]
  },
  {
   "title": "bytes_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(bytes_received_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} bytes_received_count"
    }
   ]
  },
  {
   "title": "connection_request_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(connection_request_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} connection_request_count"
    }
   ]
  },
  {
   "title": "num_alive_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_alive_connections{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} num_alive_connections"
    }
   ]
  },
  {
   "title": "connection_rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(connection_rejected{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} connection_rejected"
    }
   ]
  },
  {
   "title": "connection_drop_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(connection_drop_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} connection_drop_count"
    }
   ]
  },
  {
   "title": "connection_drop_probability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "connection_drop_probability{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} connection_drop_probability"
    }
   ]
  },
  {
   "title": "sessionless_connections_expired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sessionless_connections_expired{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} sessionless_connections_expired"
    }
   ]
  },
  {
   "title": "connection_token_deficit",
   "type": "graph",
   "description": "how much tokens deficit per sec, during connection throttling",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(connection_token_deficit_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} connection_token_deficit"
    }
   ]
  },
  { "title": "Disk/Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "open_file_descriptor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "open_file_descriptor_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}}"
    }
   ]
  },
  {
   "title": "fsync_time / fsync_rate",
   "type": "graph",
   "description": "frequency and the average time for FSYNC",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "fsynctime{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} fsynctime quantile={{quantile}}"
    },
    {
     "expr": "irate(fsynctime_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} fsynctime_count_rate"
    }
   ]
  },
  {
   "title": "snapshot_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "snapshottime{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} snapshot_time quantile={{quantile}}"
    },
    {
     "expr": "increase(snapshottime_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} snapshottime_count_rate"
    }
   ]
  },
  { "title": "Prep_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "prep_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(prep_process_time_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(prep_process_time_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} prep_process_time"
    }
   ]
  },
  {
   "title": "prep_processor_queue_time quantile=0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 134 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "prep_processor_queue_time_ms{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\", quantile=\"0.99\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} prep_processor_queue_time_ms quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "prep_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(prep_processor_queue_size_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} prep_processor_queue_size"
    }
   ]
  },
  {
   "title": "prep_processor_request_queued",
   "type": "graph",
   "description": "queued per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(prep_processor_request_queued{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} prep_processor_request_queued"
    }
   ]
  },
  {
   "title": "outstanding_changes queued / removed ",
   "type": "graph",
   "description": "changes per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(outstanding_changes_queued{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} outstanding_changes_queued"
    },
    {
     "expr": "irate(outstanding_changes_removed{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} outstanding_changes_removed"
    }
   ]
  },
  {
   "title": "close_session_prep_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 142 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "close_session_prep_time{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\", quantile=\"0.99\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} close_session_prep_time quantile={{quantile}}"
    }
   ]
  },
  { "title": "Sync_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "sync_process_time",
   "type": "graph",
   "description": "milliseconds per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(sync_process_time_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])/increase(sync_process_time_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} sync_process_time"
    }
   ]
  },
  {
   "title": "sync_processor_queue_flush_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 151 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sync_processor_queue_flush_time_ms{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} sync_processor_queue_flush_time quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "sync_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sync_processor_queue_size_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(sync_processor_queue_size_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} sync_processor_queue_size"
    }
   ]
  },
  {
   "title": "sync_processor_request_queued",
   "type": "graph",
   "description": "queued requests per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sync_processor_request_queued{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} sync_processor_request_queued"
    }
   ]
  },
  {
   "title": "sync_processor_batch_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 159 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(sync_processor_batch_size_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(sync_processor_batch_size_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} sync_processor_batch_size"
    }
   ]
  },
  { "title": "Commit_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 } },
  {
   "title": "commit_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(commit_process_time_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(commit_process_time_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} commit_process_time"
    },
    {
     "expr": "increase(read_commitproc_time_ms_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(read_commitproc_time_ms_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} read_commitproc_time"
    },
    {
     "expr": "increase(write_commitproc_time_ms_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(write_commitproc_time_ms_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} write_commitproc_time"
    }
   ]
  },
  {
   "title": "commit_proc_req_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(write_commit_proc_req_queued_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} write_commit_proc_req_queued"
    },
    {
     "expr": "irate(read_commit_proc_req_queued_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} read_commit_proc_req_queued"
    },
    {
     "expr": "irate(commit_commit_proc_req_queued_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} commit_commit_proc_req_queued"
    }
   ]
  },
  {
   "title": "requests_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(requests_in_session_queue_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} requests_in_session_queue"
    }
   ]
  },
  {
   "title": "commit_proc_issued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(read_commit_proc_issued_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} read_commit_proc_issued"
    },
    {
     "expr": "rate(write_commit_proc_issued_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} write_commit_proc_issued"
    }
   ]
  },
  {
   "title": "concurrent_request_processing_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(concurrent_request_processing_in_commit_processor_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} concurrent_request_processing_in_commit_processor"
    }
   ]
  },
  {
   "title": "time_waiting_empty_pool_in_commit_processor_read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_waiting_empty_pool_in_commit_processor_read_ms_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} time_waiting_empty_pool_in_commit_processor_read"
    }
   ]
  },
  {
   "title": "pending_session_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pending_session_queue_size_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} pending_session_queue_size"
    }
   ]
  },
  {
   "title": "local_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(local_write_committed_time_ms_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} local_write_committed_time_ms"
    }
   ]
  },
  {
   "title": "server_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(server_write_committed_time_ms_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} server_write_committed_time"
    }
   ]
  },
  {
   "title": "write_batch_time_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_batch_time_in_commit_processor_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} write_batch_time_in_commit_processor"
    }
   ]
  },
  {
   "title": "reads_after_write_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(reads_after_write_in_session_queue_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} reads_after_write_in_session_queue"
    }
   ]
  },
  {
   "title": "session_queues_drained",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 192 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(session_queues_drained_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} session_queues_drained"
    }
   ]
  },
  {
   "title": "reads_issued_from_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(reads_issued_from_session_queue_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} reads_issued_from_session_queue"
    }
   ]
  },
  {
   "title": "request_commit_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_commit_queued{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} request_commit_queued"
    }
   ]
  },
  { "title": "Final_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 208 } },
  {
   "title": "write_final_proc_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_final_proc_time_ms_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} write_final_proc_time_ms"
    }
   ]
  },
  {
   "title": "read_final_proc_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(read_final_proc_time_ms_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[5m])",
     "legendFormat": "{{pod_name}}.{{namespace}} read_final_proc_time_ms"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 217 } },
  {
   "title": "read_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "readlatency{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\", quantile=\"0.99\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} readlatency quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "update_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "updatelatency{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\", quantile=\"0.99\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} updatelatency quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "max_min_avg_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "min_latency{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} min_latency"
    },
    {
     "expr": "max_latency{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} max_latency"
    },
    {
     "expr": "avg_latency{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} avg_latency"
    }
   ]
  },
  {
   "title": "proposal_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(proposal_latency_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(proposal_latency_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} proposal_latency"
    }
   ]
  },
  {
   "title": "quorum_ack_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(quorum_ack_latency_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(quorum_ack_latency_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} quorum_ack_latency"
    }
   ]
  },
  {
   "title": "ack_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ack_latency{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} ack_latency_sum"
    }
   ]
  },
  {
   "title": "propagation_latency",
   "type": "graph",
   "description": "normalized latency by last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(propagation_latency_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(propagation_latency_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} propagation_latency"
    }
   ]
  },
  {
   "title": "commit_propagation_latency",
   "type": "graph",
   "description": "normalized latency by last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 242 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(commit_propagation_latency_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(commit_propagation_latency_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} commit_propagation_latency"
    }
   ]
  },
  {
   "title": "proposal_ack_creation_latency",
   "type": "graph",
   "description": "normalized latency by last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 250 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(proposal_ack_creation_latency_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m]) / increase(proposal_ack_creation_latency_count{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} proposal_ack_creation_latency-{{quantile}}"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 258 } },
  {
   "title": "tls_handshake",
   "type": "graph",
   "description": "ops per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(tls_handshake_exceeded{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} tls_handshake_exceeded"
    },
    {
     "expr": "irate(outstanding_tls_handshake{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} outstanding_tls_handshake"
    }
   ]
  },
  {
   "title": "ensemble_auth",
   "type": "graph",
   "description": "ops per second",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ensemble_auth_fail{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} ensemble_auth_fail"
    },
    {
     "expr": "irate(ensemble_auth_success{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} ensemble_auth_success"
    },
    {
     "expr": "irate(ensemble_auth_skip{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} ensemble_auth_skip"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 267 } },
  {
   "title": "jvm_classes_loaded",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 268 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_classes_loaded{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 268 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_current{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_deadlocked",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 268 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_deadlocked{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "jvm_pause_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 276 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_pause_time_ms{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} jvm_pause_time_ms quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 276 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}[1m])",
     "legendFormat": "{{pod_name}}.{{namespace}} gc:{{gc}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 276 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} state:{{state}}"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 284 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=~\"$namespace\",pod_name=~\"$pod_name\",job=~\"$job\"}",
     "legendFormat": "{{pod_name}}.{{namespace}} pool:{{pool}}"
    }
   ]
  }
 ]
}