FROM apache/superset:737d4dcf0cd36eb4c2c54a4e4d3ea5b0761810a0

RUN pip install \
      psycopg2==2.8.5 \
      Authlib~=0.15.3 \
      pyjwt \
      pybigquery \
      redis==3.2.1 \
      typing-extensions~=3.10 \
      snowflake-sqlalchemy~=1.2.4