FROM apache/superset:3c41ff68a43b5ab6b871226a73de9f2129d64766

RUN pip install \
      psycopg2==2.8.5 \
      Authlib~=0.15.3 \
      pyjwt \
      pybigquery \
      redis==3.2.1 \
      typing-extensions~=3.10 \
      snowflake-sqlalchemy~=1.2.4