{
 "title": "KubeRay - Controller Runtime Controllers",
 "description": "Profiling performance-related metrics based on controller-runtime.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(ray_operator_clusters_created_total, namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(controller_runtime_active_workers{namespace=\"$Namespace\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Reconciling Latency Quantile (in 1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$Service\"}[$__rate_interval])) by (job,le,controller))",
     "legendFormat": "{{job}} - {{controller}} - 50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=~\"$Service\"}[$__rate_interval])) by (job,le,controller))",
     "legendFormat": "{{job}} - {{controller}} - 95%"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{job=~\"$Service\"}[$__rate_interval])) by (job,controller) / sum(rate(controller_runtime_reconcile_time_seconds_count{job=~\"$Service\"}[$__rate_interval])) by (job,controller)",
     "legendFormat": "{{job}} - {{controller}} - mean"
    }
   ]
  },
  {
   "title": "Reconciling Count (in 1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(increase(controller_runtime_reconcile_total{job=\"$Service\"}[$__rate_interval])) by (job,controller,result))",
     "legendFormat": "{{job}}- {{controller}} - {{result}}"
    }
   ]
  },
  {
   "title": "Reconciling Latency Over Time (in 1m)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=~\"$Service\"}[$__rate_interval])) by (job,le,controller)"
    }
   ]
  },
  { "title": "Ray Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cluster Created Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(ray_operator_clusters_created_total{service=\"$Service\"}[30m])"
    }
   ]
  },
  {
   "title": "Cluster Created Successful Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rate(ray_operator_clusters_successful_total{service=\"$Service\"}[30m])"
    }
   ]
  },
  {
   "title": "Cluster Created Failure Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rate(ray_operator_clusters_failed_total{service=\"$Service\"}[30m])"
    }
   ]
  }
 ]
}