{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(pg_exporter_last_scrape_duration_seconds, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(pg_up{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{namespace=\"$namespace\", pod=\"$pod\"}, datname)"
   },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "pg_static{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{namespace=\"$namespace\", pod=\"$pod\"} * 1000"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{namespace=\"$namespace\", datname=~\"$datname\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_connections{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average container CPU usage.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"postgres\"}[$__rate_interval])",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", container=\"postgres\", resource=\"cpu\", job=\"kube-state-metrics\"}",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", container=\"postgres\", resource=\"cpu\", job=\"kube-state-metrics\"}",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory Usage in bytes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"postgres\"}",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", pod=\"$pod\", container=\"postgres\", resource=\"memory\", job=\"kube-state-metrics\"}",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", pod=\"$pod\", container=\"postgres\", resource=\"memory\", job=\"kube-state-metrics\"}",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Total Inodes",
   "type": "graph",
   "description": "Number of inodes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_fs_inodes_total{namespace=\"$namespace\", pod=\"$pod\", container=\"postgres\"}",
     "legendFormat": "Total Inodes"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "pg_settings_seq_page_cost" }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{pod=\"$pod\"}"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", pod=~\"$pod\", state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{pod=\"$pod\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{pod=\"$pod\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", pod=~\"$pod\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", pod=~\"$pod\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", pod=~\"$pod\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$datname\", pod=~\"$pod\", mode=~\"$mode\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", pod=~\"$pod\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", pod=~\"$pod\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", pod=~\"$pod\"} != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{pod=\"$pod\", datname=~\"$datname\"} / (pg_stat_database_blks_read{pod=\"$pod\", datname=~\"$datname\"} + pg_stat_database_blks_hit{pod=\"$pod\", datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{pod=\"$pod\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{pod=\"$pod\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{pod=\"$pod\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{pod=\"$pod\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{pod=\"$pod\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{pod=\"$pod\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{pod=\"$pod\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{pod=\"$pod\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{pod=\"$pod\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{pod=\"$pod\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}